config/routes.rb
Rails.application.routes.draw do
  resources :manofacturers
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  resources :products
  resources :causes
  resources :pictures
  resources :categories
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}
  root 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/cause.rb
class Cause < ActiveRecord::Base
	mount_uploader :logo, LogoUploader

	has_many :products
end

app/models/manofacturer.rb
class Manofacturer < ActiveRecord::Base
	has_many :products
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
	has_many :orders
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	mount_uploader :upimg, UpimgUploader

	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :cause
	belongs_to :category
	belongs_to :manofacturer
	has_many :pictures
	has_many :order_items

  	default_scope { where(active: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

         validates :doc_type, inclusion: { in: %w(PASS TI CC CE),
    		message: "%{value} no es un tipo valido" }, on: :update
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/manofacturers_controller.rb
class ManofacturersController < ApplicationController
  before_action :set_manofacturer, only: [:show, :edit, :update, :destroy]

  # GET /manofacturers
  # GET /manofacturers.json
  def index
    @manofacturers = Manofacturer.all
  end

  # GET /manofacturers/1
  # GET /manofacturers/1.json
  def show
  end

  # GET /manofacturers/new
  def new
    @manofacturer = Manofacturer.new
  end

  # GET /manofacturers/1/edit
  def edit
  end

  # POST /manofacturers
  # POST /manofacturers.json
  def create
    @manofacturer = Manofacturer.new(manofacturer_params)

    respond_to do |format|
      if @manofacturer.save
        format.html { redirect_to @manofacturer, notice: 'Manofacturer was successfully created.' }
        format.json { render :show, status: :created, location: @manofacturer }
      else
        format.html { render :new }
        format.json { render json: @manofacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manofacturers/1
  # PATCH/PUT /manofacturers/1.json
  def update
    respond_to do |format|
      if @manofacturer.update(manofacturer_params)
        format.html { redirect_to @manofacturer, notice: 'Manofacturer was successfully updated.' }
        format.json { render :show, status: :ok, location: @manofacturer }
      else
        format.html { render :edit }
        format.json { render json: @manofacturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manofacturers/1
  # DELETE /manofacturers/1.json
  def destroy
    @manofacturer.destroy
    respond_to do |format|
      format.html { redirect_to manofacturers_url, notice: 'Manofacturer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manofacturer
      @manofacturer = Manofacturer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manofacturer_params
      params.require(:manofacturer).permit(:name, :video)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/causes_helper.rb
module CausesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manofacturers_helper.rb
module ManofacturersHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/manofacturers/_form.html.erb
<%= form_for(@manofacturer) do |f| %>
  <% if @manofacturer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manofacturer.errors.count, "error") %> prohibited this manofacturer from being saved:</h2>

      <ul>
      <% @manofacturer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :video %><br>
    <%= f.text_field :video %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/manofacturers/edit.html.erb
<h1>Editing Manofacturer</h1>

<%= render 'form' %>

<%= link_to 'Show', @manofacturer %> |
<%= link_to 'Back', manofacturers_path %>

app/views/manofacturers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Manofacturers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manofacturers.each do |manofacturer| %>
      <tr>
        <td><%= manofacturer.name %></td>
        <td><%= manofacturer.video %></td>
        <td><%= link_to 'Show', manofacturer %></td>
        <td><%= link_to 'Edit', edit_manofacturer_path(manofacturer) %></td>
        <td><%= link_to 'Destroy', manofacturer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manofacturer', new_manofacturer_path %>

app/views/manofacturers/new.html.erb
<h1>New Manofacturer</h1>

<%= render 'form' %>

<%= link_to 'Back', manofacturers_path %>

app/views/manofacturers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @manofacturer.name %>
</p>

<p>
  <strong>Video:</strong>
  <%= @manofacturer.video %>
</p>

<%= link_to 'Edit', edit_manofacturer_path(@manofacturer) %> |
<%= link_to 'Back', manofacturers_path %>