config/routes.rb
Rails.application.routes.draw do
  resources :manofacturers
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  resources :products
  resources :causes
  resources :pictures
  resources :categories
  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}
  root 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/cause.rb
class Cause < ActiveRecord::Base
	mount_uploader :logo, LogoUploader

	has_many :products
end

app/models/manofacturer.rb
class Manofacturer < ActiveRecord::Base
	has_many :products
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
	has_many :orders
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	mount_uploader :upimg, UpimgUploader

	belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :cause
	belongs_to :category
	belongs_to :manofacturer
	has_many :pictures
	has_many :order_items

  	default_scope { where(active: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

         validates :doc_type, inclusion: { in: %w(PASS TI CC CE),
    		message: "%{value} no es un tipo valido" }, on: :update
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/causes_helper.rb
module CausesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bepart</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
	  <div class="container">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <strong><%= link_to "Bepart", root_path, class: "navbar-brand" %></strong>
		    </div>

		    <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li><a href="#">Acerca de</a></li>
		     		<li><%= link_to 'Comprar', products_path %></li>
		     		<li><a href="#">Newsletter</a></li>
		     		<li><a href="#">Miembro?</a></li>
		     		<% if user_signed_in? %>
		                <li class="hidden-lg"><a href="#"><%= current_user.User_name %></a></li>
		                <li class="hidden-lg"><%= link_to('Mi perfil', edit_user_registration_path) %></li>
		                <li class="hidden-lg"><%= link_to('Desconectar', destroy_user_session_path, :method => :delete) %></li>
		            <% end %>
		      </ul>
		      <form class="navbar-form navbar-left" role="search">
		        <div class="form-group">
		          <input type="text" class="form-control" placeholder="Search">
		        </div>
		        <button type="submit" class="btn btn-default">Submit</button>
		      </form>
		      <ul class="nav navbar-nav navbar-right">
		        <% if user_signed_in? %>
		        	<li><h1 class="cart-text pucart"><%= render 'layouts/cart_text' %></h1></li>
              		<li class="dropdown hidden-xs">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.User_name %><span class="caret"></span></a>
			          <ul class="dropdown-menu">
			            <li><%= link_to('Mi perfil', edit_user_registration_path) %></li>
			            <li role="separator" class="divider"></li>
			            <li><%= link_to('Desconectar', destroy_user_session_path, :method => :delete) %></li>
			          </ul>
			        </li>
				<% else %>
				  <li>
				  		<%= link_to "Iniciar sesión", "#", data: {toggle: "modal", target: "#myModal"} %>
				  </li>
				  <li>
				  		<%= link_to "Regístrate!", "#", data: {toggle: "modal", target: "#register-modal"} %>
				  </li>
				<% end %>
		      </ul>
		    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

	<%= render partial: 'partials/login' %>
	<%= render partial: 'partials/register' %>

<%= yield %>

</body>
</html>

app/views/partials/_login.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Login</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'partials/login_form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_login_form.html.erb
<%= form_for(User.new, as: :user, url: session_path(:user)) do |f| %>
  <div class="alert alert-danger errors" style="display: none"></div>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "Log in", class: "btn btn-success btn-lg" %>
  </div>
<% end %>

app/views/partials/_register.html.erb
<div class="modal fade" id="register-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Register</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'partials/register_form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_register_form.html.erb
<%= form_for(User.new, as: :user, url: registration_path(:user), html: { class: "registration-form" }) do |f| %>
  <div class="alert alert-danger errors" style="display: none"></div>
  
  <div class="form-group">
    <%= f.label :User_name %><br />
    <%= f.text_field :User_name, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up", class: "btn btn-success btn-lg" %>
  </div>
<% end %>